# @file
# .travis.yml - PKP Plugins Integration

language: php
dist: trusty

addons:
  apt:
    update: true

sudo: required

php:
  - 7.2
env:
  - APPLICATION=ojs BRANCH=master TEST=mysql
  - APPLICATION=ojs BRANCH=master TEST=pgsql
  - APPLICATION=omp BRANCH=master TEST=mysql
  - APPLICATION=omp BRANCH=master TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  # Prepare server environment
  - source lib/pkp/tools/travis/start-xvfb.sh
  - lib/pkp/tools/travis/start-selenium.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Make sure we're using the current checkout of this repo rather than the built-in OJS/OMP version
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/customHeader
  # Install OJS/OMP & prep data environment
  - lib/pkp/lib/vendor/phpunit/phpunit/phpunit --configuration lib/pkp/tests/phpunit-env1.xml --filter "InstallationTest|CreateContextTest" tests/data
  - lib/pkp/tools/travis/dump-database.sh
script:
  - set +xe
  - lib/pkp/lib/vendor/phpunit/phpunit/phpunit --debug -v --configuration lib/pkp/tests/phpunit-env2.xml plugins/generic/customHeader/tests/functional/CustomHeaderFunctionalTest.php
after_failure:
  - sudo apt-get install sharutils
  - tar cz lib/pkp/tests/results | uuencode -m -
